version: "3.3"
services:
  cloudflared:
    network_mode: host
    container_name: cloudflare-tunnels
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $TOKEN
    restart: always
networks: {}